server:
  servlet:
    context-path: /picture
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

mybatis:
  type-aliases-package: com.xxxx.entity
  mapper-locations: classpath:/mappers/*.xml
